name: Deploy Go

on:
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o backend-bin ./cmd/server

      - name: Transfer binary (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend-bin"
          target: "/root/DeadLionBackend"

      - name: Restart Service via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x /root/DeadLionBackend/backend-bin
            sudo systemctl restart go-backend.service